services:
  consul:
    image: consul:1.15
    container_name: consul-2
    network_mode: host
    restart: unless-stopped

    volumes:
      - consul2_data:/consul/data

    command: >
      agent -server -ui
      -node=consul-2
      -bootstrap-expect=2
      -datacenter=dc1
      -bind=10.1.11.41
      -advertise=10.1.11.41
      -retry-join=10.1.11.40
      -client=0.0.0.0

    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  consul2_data:
